# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt deneme 1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1040, 640)
        MainWindow.setMinimumSize(QtCore.QSize(1040, 640))
        MainWindow.setMaximumSize(QtCore.QSize(1040, 640))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1040, 611))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 0, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.fontComboBox = QtWidgets.QFontComboBox(self.gridLayoutWidget)
        self.fontComboBox.setObjectName("fontComboBox")
        self.gridLayout.addWidget(self.fontComboBox, 0, 3, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setEnabled(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 0, 6, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 5, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 1, 0, 1, 7)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.menuYeni = QtWidgets.QMenu(self.menubar)
        self.menuYeni.setObjectName("menuYeni")
        self.menuA = QtWidgets.QMenu(self.menubar)
        self.menuA.setObjectName("menuA")
        self.menuKaydet = QtWidgets.QMenu(self.menubar)
        self.menuKaydet.setObjectName("menuKaydet")
        self.menuKapat = QtWidgets.QMenu(self.menubar)
        self.menuKapat.setObjectName("menuKapat")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuYeni.menuAction())
        self.menubar.addAction(self.menuA.menuAction())
        self.menubar.addAction(self.menuKaydet.menuAction())
        self.menubar.addAction(self.menuKapat.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Yapıştır"))
        self.pushButton_5.setText(_translate("MainWindow", "Kes"))
        self.pushButton_4.setText(_translate("MainWindow", "Kopyala"))
        self.pushButton_3.setText(_translate("MainWindow", "İtalik_yazı"))
        self.pushButton_2.setText(_translate("MainWindow", "Kalın_yazı"))
        self.menuYeni.setTitle(_translate("MainWindow", "Yeni"))
        self.menuA.setTitle(_translate("MainWindow", "Aç"))
        self.menuKaydet.setTitle(_translate("MainWindow", "Kaydet"))
        self.menuKapat.setTitle(_translate("MainWindow", "Kapat"))